name: Code Quality Checks

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint -- --max-warnings=0
        continue-on-error: true
        
      - name: Check unused exports with ts-prune
        run: npm run unused-exports
        
      - name: Check for duplicate code
        run: npm run find-duplicates
